### ISSUE TITLE
`The security token included in the request is invalid` when running rspec

### ISSUE THREAD

**Issue by BilalBudhani** [OceanDev/ocean-dynamo#21]
I've installed `fake_dynamo v 0.1.3` and tried running the specs with `bundle exec rspec` and `bundle exec rspec --fail-fast` both commands but, it throws the same error for every test case. 

```ruby
1) OceanDynamo::Associations::CollectionAssociation should inherit from Association
     Failure/Error: @o = Owner.create!
     AWS::DynamoDB::Errors::UnrecognizedClientException:
       The security token included in the request is invalid.
     # (eval):3:in `describe_table'
     # ./lib/ocean-dynamo/tables.rb:48:in `establish_db_connection'
     # ./lib/ocean-dynamo/persistence.rb:62:in `_late_connect?'
     # ./lib/ocean-dynamo/persistence.rb:274:in `_late_connect?'
     # ./lib/ocean-dynamo/persistence.rb:279:in `dynamo_persist'
     # ./lib/ocean-dynamo/persistence.rb:163:in `block (3 levels) in create'
     # ./lib/ocean-dynamo/persistence.rb:154:in `block (2 levels) in create'
     # ./lib/ocean-dynamo/persistence.rb:153:in `block in create'
     # ./lib/ocean-dynamo/persistence.rb:152:in `create'
     # ./lib/ocean-dynamo/persistence.rb:145:in `create_or_update'
     # ./lib/ocean-dynamo/persistence.rb:125:in `save!'
     # ./lib/ocean-dynamo/persistence.rb:28:in `create!'
     # ./spec/dynamo/associations/collection_association_spec.rb:29:in `block (2 levels) in <module:Associations>'

  2) OceanDynamo::Associations::CollectionAssociation should have a reset method which sets @target to []
     Failure/Error: @o = Owner.create!
     AWS::DynamoDB::Errors::UnrecognizedClientException:
       The security token included in the request is invalid.
     # (eval):3:in `describe_table'
     # ./lib/ocean-dynamo/tables.rb:48:in `establish_db_connection'
     # ./lib/ocean-dynamo/persistence.rb:62:in `_late_connect?'
     # ./lib/ocean-dynamo/persistence.rb:274:in `_late_connect?'
     # ./lib/ocean-dynamo/persistence.rb:279:in `dynamo_persist'
     # ./lib/ocean-dynamo/persistence.rb:163:in `block (3 levels) in create'
     # ./lib/ocean-dynamo/persistence.rb:154:in `block (2 levels) in create'
     # ./lib/ocean-dynamo/persistence.rb:153:in `block in create'
     # ./lib/ocean-dynamo/persistence.rb:152:in `create'
     # ./lib/ocean-dynamo/persistence.rb:145:in `create_or_update'
     # ./lib/ocean-dynamo/persistence.rb:125:in `save!'
     # ./lib/ocean-dynamo/persistence.rb:28:in `create!'
     # ./spec/dynamo/associations/collection_association_spec.rb:29:in `block (2 levels) in <module:Associations>'
```

What should I do to get the specs passing?

**Comment by PeterBengtson** [comment]
It’s difficult to say, as you don’t specify the Ruby version or the Rails version, but looking at the error message you get I’d wager a guess that you’re running against AWS and not against your instance of fake_dynamo.

Take a look at spec/dummy/config/aws.yml and make sure the last three sections specify local and not amazon.

Alternatively, set up an AWS account and use its provided credentials. Both works.

**Comment by BilalBudhani** [comment]
@PeterBengtson thanks got it working.
